### ISSUE TITLE
Monolog errors after deploy

### ISSUE THREAD

**Issue by cyannick** [shpasser/GaeSupportL5#39]
Hello

After successfully installing your plugin, my website deployed successfully to GAE.
I'm able to migrate my tables in the Google Cloud Storage.

When I now try to register, the Monolog is trying to export a logfile in <bucket>/storage/logs

I found this post with almost the same issues:
https://github.com/shpasser/GaeSupportL5/issues/18

I tried to find useful configuration settings, unfortunately without success.

I'm running Laravel 5.1 and your GaeSupportL5 as of today.

Stacktrace in the GAE log:

PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "gs://p-app/storage/logs/laravel.log" could not be opened: failed to open stream: "\google\appengine\ext\cloud_storage_streams\CloudStorageStreamWrapper::stream_open" call failed' in /base/data/home/apps/e~pingvalue-app/dev-001.388656046154908935/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87
Stack trace:
#0 /base/data/home/apps/e~p-app/dev-001.388656046154908935/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /base/data/home/apps/e~p-app/dev-001.388656046154908935/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /base/data/home/apps/e~p-app/dev-001.388656046154908935/vendor/monolog/monolog/src/Monolog/Logger.php(565): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 /base/data/home/apps/e~p-app/dev-001.388656046 in /base/data/home/apps/e~p-app/dev-001.388656046154908935/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 87

**Comment by cyannick** [comment]
Okay I managed to change the log to "syslog" in the file config/app.php, afterwards I runned the command: php artisan config:cache to regenerate the bootstrap/cache/config.php file.

Now I finally get my errors printed in the HTML page instead of Google App Engine logs.

It looks like my Laravel project is referring to files on my localhost in the file_put_contents function:

in Filesystem.php line 81
at HandleExceptions->handleError('2', 'file_put_contents(C:\xampp\htdocs\project\storage\framework/sessions/6e3ca6227d6722d25186e9da4845ca28d770c019): The local filesystem is readonly, open failed', '/base/data/home/apps/e~pingvalue-app/dev-001.388658000960999524/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php', '81', array('path' => 'C:\xampp\htdocs\project\storage\framework/sessions/6e3ca6227d6722d25186e9da4845ca28d770c019', 'contents' => 'a:3:{s:6:"_token";s:40:"te7dN53Jttf6cwdMN3oNpoiWCXEZbmLjqvC6eOse";s:9:"_sf2_meta";a:3:{s:1:"u";i:1447863924;s:1:"c";i:1447863924;s:1:"l";s:1:"0";}s:5:"flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}', 'lock' => true))
at file_put_contents('C:\xampp\htdocs\project\storage\framework/sessions/6e3ca6227d6722d25186e9da4845ca28d770c019', 'a:3:{s:6:"_token";s:40:"te7dN53Jttf6cwdMN3oNpoiWCXEZbmLjqvC6eOse";s:9:"_sf2_meta";a:3:{s:1:"u";i:1447863924;s:1:"c";i:1447863924;s:1:"l";s:1:"0";}s:5:"flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}', '2') in Filesystem.php line 81
at Filesystem->put('C:\xampp\htdocs\project\storage\framework/sessions/6e3ca6227d6722d25186e9da4845ca28d770c019', 'a:3:{s:6:"_token";s:40:"te7dN53Jttf6cwdMN3oNpoiWCXEZbmLjqvC6eOse";s:9:"_sf2_meta";a:3:{s:1:"u";i:1447863924;s:1:"c";i:1447863924;s:1:"l";s:1:"0";}s:5:"flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}', true) in FileSessionHandler.php line 71
at FileSessionHandler->write('6e3ca6227d6722d25186e9da4845ca28d770c019', 'a:3:{s:6:"_token";s:40:"te7dN53Jttf6cwdMN3oNpoiWCXEZbmLjqvC6eOse";s:9:"_sf2_meta";a:3:{s:1:"u";i:1447863924;s:1:"c";i:1447863924;s:1:"l";s:1:"0";}s:5:"flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}') in Store.php line 262
at Store->save() in StartSession.php line 88
at StartSession->terminate(object(Request), object(Response)) in Kernel.php line 145
at Kernel->terminate(object(Request), object(Response)) in index.php line 58

**Comment by shpasser** [comment]
I think that the issue might be, that you deployed the app with wrong `.env` file. Before deploying the app you need to copy the generated `.env.production` file and rename it to `.env`. As for the other issue, generation of `config.php` using `artisan config:cache` is not suitable for GAE, please use `php artisan gae:setup --cache-config your-app-id`(optimizations section in the readme file).

**Comment by shpasser** [comment]
The chat can be also useful:
https://gitter.im/shpasser/GaeSupportL5

**Comment by cyannick** [comment]
Okay

I think I figured out my problem, I was making config files by using your tool, then loading my website locally before deploy, etc. This made the bootstrap/cache/config.php file corrupt/wrong for GAE or something.

I understood from research that GAE only allows 'log' => 'syslog', default was 'single' in my config/app.php.

After I manually changed it to syslog, I re-runned your command to re-generate the bootstrap/cache/config.php file:
php artisan gae:setup --cache-config pingvalue-app

At first I didn't notice from your documentation that every time I want to deploy, I have to regenerate the bootstrap/cache/config.php file.

I am now able to deploy to different environments, migrate my databases locally, ...

Thank you!

**Comment by shpasser** [comment]
Actually the generated `.env.production` and `.env.local` files contain the right values for `APP_LOG` variable, which is used by default by the latest Laravel 5.1 in `config/app.php`. Even before `APP_LOG` variable existed the package used `LOG_HANDLER` variable in order to set log handler. Of course, at that time the package also modified `config/app.php` to use `LOG_HANDLER` variable.

Thanks.

**Comment by cyannick** [comment]
Hi shpasser

Indeed, i noticed the APP_LOG in the .env files but for some odd reason this didn't work for me, that's why I edited it manually.

I'll check back tomorrow with the development team to ensure we use Laravel 5.1

**Comment by shpasser** [comment]
I suspect that you created your project before the latest revision of Laravel 5.1 was committed, meaning your `config/app.php` file will remain as it is now even if you update to the latest revision of the framework. Unless you recreate the project.

I will try to see if I can change `gae:setup` command, so it will handle the case.

**Comment by shpasser** [comment]
The issue was reopened. Working on a change to support the older versions of `config/app.php`

**Comment by shpasser** [comment]
Please update to version 1.4.10, it should support the older `config/app.php` as well.

**Comment by cyannick** [comment]
Yes, I think we updated from 5.0 to 5.1. I'll test this on monday.

Thank you for your fast support!!

**Comment by cyannick** [comment]
It works, thank you!
